### PR TITLE
Task 0008: Appointment API

### PR DESCRIPTION
**Pull request by migrivros**

### CODE REVIEW

**Review by jbl0107 — CHANGES_REQUESTED** [review]
A 500 error occurs in the delete method when the appointment id doesn´t exist.

**Review by jbl0107 — APPROVED** [review]
Now everything works correctly.

**Review by fraorober — APPROVED** [review]
I have reviewed all funcionalities on postman and these are working good

**Review by fraorober — APPROVED** [review]
I have checked all methods of controller on postman and these are woking after resolving conflicts.

**Review by jbl0107 — APPROVED** [review]
All right.

**Review by Damaris1008 — APPROVED** [review]
All endpoints from AppointmentController have been tested in Postman and they are working properly.

**Pull request merged**
