### PR TITLE
Task 0006: Academic Experience API

### PR DESCRIPTION
**Pull request by fraorober**

### CODE REVIEW

**Review by jbl0107 — CHANGES_REQUESTED** [review]
A 500 error occurs in the getAcademicExperienceByVolunteerUsername and getAcademicExperienceByBeneficiaryUsername methods when the volunteer or beneficiary in question doesn´t have any academicExperience or when the username doesn´t exist.

**Review by migrivros — APPROVED** [review]
The API about academic experience works very well. Nice job!

**Review by migrivros — CHANGES_REQUESTED** [review]
A 500 error occurs in the getAcademicExperienceByVolunteerUsername method when the volunteer in question doesn´t have any academicExperience. You check condition for ONG like user logged, but its necessary to check too for the volunteer like user logged.

**Review by migrivros — APPROVED** [review]
Now the API works correctly. God job!

**Review by jbl0107 — APPROVED** [review]
All right.

**Pull request merged**
